### ISSUE TITLE
Game is not saved when Android moves Klooni into cache

### ISSUE THREAD

**Issue by StefanBrand** [LonamiWebs/Klooni1010#1]
Hi,

I switched to a different app for a while and when I went back to Klooni through the "Recent Apps" view (left soft key) I couldn't resume the game. Klooni only showed me the start screen.

I assumed that Android in the meanwhile had killed Kloonie and Klooni had nowhere to resume the game from. 

###My setup
- Android KitKat 4.4.2
- Fairphone 1, 1GB RAM
- MT6589

PS: Thank you for porting this great game, it's been keeping me busy lately! :)

**Comment by XyLoNaMiyX** [comment]
> I couldn't resume the game. Klooni only showed me the start screen.

I assume what you mean here is that you would like to whole current screen (board state, colors, current and high-score) to be saved if the application is left? This is somewhat harder than only saving the high-score (currently, it's saved when the menu is opened), but I will do take a look into it and let you know.

> Thank you for porting this great game

Thank **you** for the positive feedback! Feel free to suggest more ideas if you have any!

**Comment by XyLoNaMiyX** [comment]
Okay, after taking a look I'm back with more things to discuss.

### Questions
1. Should this only happen for Android or desktop too (i.e. leave the application, but being able to open it and have the last game)?
2. It is not easy to determine when the game state should be saved. Currently I have 3 places where I could check it:
    1. When the screen is **hidden**. This implies when you go to the customize menu or back to the main menu. However, this does *not* get called when you leave the game.
    2. When the game is **paused**. This is when you leave the game. However, if you go back "quick" enough the state won't be lost so having saved it would be useless. Furthermore this doesn't get called if you leave the game *after* it was hidden.
    3. When the game is **disposed**. This *should* be called when the game is truly exited. However, it was never called on the tests I did.
3. Saving a file (which is not the same as some preferences, such as high score) would obviously not work on the web, although there are no plans for it yet it wouldn't make much sense anyway.
4. This is more of an excuse, but in most games if you leave the game while playing a level, next time you're back, it won't restart in the exact same place.
5. Should you be able to also leave the game (i.e. to the main screen) while conserving the state? What if you intended to leave and start over?

### Conclusion
Perhaps I could save the game state when it's paused (which, sadly, I can't tell if the game is really going to be closed or not so sometimes it will be useless). If you go back to the game and you don't appear on the main screen, then it was not needed, and thus the file is deleted silently. If, on the other hand, you appear on the main screen, then the game, should load directly or after you hit play?

**Comment by StefanBrand** [comment]
>1. Should this only happen for Android or desktop too (i.e. leave the
>application, but being able to open it and have the last game)?

I haven't played the game on desktop, so I can't really tell. Got to know it through F-Droid.

>2. It is not easy to determine when the game state should be saved.

It might be worth it to look at K-9 Mail's code. As soon as I press the left soft key, the message I'm typing at the moment is saved to drafts. For real multitasking it would be great if Klooni behaved in the same way.

>5. Should you be able to also leave the game (i.e. to the main screen)
>while conserving the state? What if you intended to leave and start
>over?

Hm... If I want to start over I can simply click the green round arrow in the pause menu.

If, on the other hand, you appear on the main screen, then
>the game, should load directly or after you hit play?

I think it would be unintuitive, if the game loaded immediately. In case there is a saved game display that one, else start a new game.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 6. Februar 2017 12:47:43 MEZ schrieb Lonami <notifications@github.com>:
>Okay, after taking a look I'm back with more things to discuss.
>
>### Questions
>1. Should this only happen for Android or desktop too (i.e. leave the
>application, but being able to open it and have the last game)?
>2. It is not easy to determine when the game state should be saved.
>Currently I have 3 places where I could check it:
>1. When the screen is **hidden**. This implies when you go to the
>customize menu or back to the main menu. However, this does *not* get
>called when you leave the game.
>2. When the game is **paused**. This is when you leave the game.
>However, if you go back "quick" enough the state won't be lost so
>having saved it would be useless. Furthermore this doesn't get called
>if you leave the game *after* it was hidden.
>3. When the game is **disposed**. This *should* be called when the game
>is truly exited. However, it was never called on the tests I did.
>3. Saving a file (which is not the same as some preferences, such as
>high score) would obviously not work on the web, although there are no
>plans for it yet it wouldn't make much sense anyway.
>4. This is more of an excuse, but in most games if you leave the game
>while playing a level, next time you're back, it won't restart in the
>exact same place.
>5. Should you be able to also leave the game (i.e. to the main screen)
>while conserving the state? What if you intended to leave and start
>over?
>
>### Conclusion
>Perhaps I could save the game state when it's paused (which, sadly, I
>can't tell if the game is really going to be closed or not so sometimes
>it will be useless). If you go back to the game and you don't appear on
>the main screen, then it was not needed, and thus the file is deleted
>silently. If, on the other hand, you appear on the main screen, then
>the game, should load directly or after you hit play?

**Comment by XyLoNaMiyX** [comment]
Make sure you open the pause menu first or the state won't get saved :)

**Comment by XyLoNaMiyX** [comment]
Just another question, should the time mode really be saved? I mean it's meant to be something... quick. It's OK if you're doing a great game on normal mode but it's somewhat harder on the time game mode.

If the time mode doesn't need to be saved it would simplify some stuff. Do you think it should be saved too? Currently, if you have a saved state for normal game mode and you play time mode, you loss the progress; and vice versa.

Opinion? Thanks!

**Comment by StefanBrand** [comment]
No, time mode doesn't need to be saved. You usually take your time for that and won't switch to another app.

It's a bummer that I need to go to the pause menu for the state to be saved. It's unintuitive in my opinion because I don't see why I need to pause a game that's not running by time. Is it not possible to don't like K-9 Mail (save as soon as app is not in focus anymore)?


-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 9. Februar 2017 20:52:22 MEZ schrieb Lonami <notifications@github.com>:
>Just another question, should the time mode really be saved? I mean
>it's meant to be something... quick. It's OK if you're doing a great
>game on normal mode but it's somewhat harder on the time game mode.
>
>If the time mode doesn't need to be saved it would simplify some stuff.
>Do you think it should be saved too? Currently, if you have a saved
>state for normal game mode and you play time mode, you loss the
>progress; and vice versa.
>
>Opinion? Thanks!

**Comment by XyLoNaMiyX** [comment]
> No, time mode doesn't need to be saved. You usually take your time for that and won't switch to another app.

Okay, awesome, thanks for the feedback. It really makes thing easier because I'm planning some way to kinda encrypt the `.sav` file a bit not to allow direct access. Actually not sure how useful that would be since you can edit the score preferences even more easily 😅.

> Is it not possible to don't like K-9 Mail (save as soon as app is not in focus anymore)?

True true, my bad, I even mentioned it. Thanks for the reminder.

**Comment by XyLoNaMiyX** [comment]
State is now saved when the game loses focus too, done on commit [`c02c00e`](https://github.com/LonamiWebs/Klooni1010/commit/c02c00ee6473d424ba3574533987d8fdf98ce68c).

**Comment by StefanBrand** [comment]
Great! :D Is there also a toaster message? If not, could you make one? It will give people feedback about their saved game.

-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 14:11:31 MEZ schrieb Lonami <notifications@github.com>:
>State is now saved when the game loses focus too, done on commit
>[`c02c00e`](https://github.com/LonamiWebs/Klooni1010/commit/c02c00ee6473d424ba3574533987d8fdf98ce68c).

**Comment by XyLoNaMiyX** [comment]
> Is there also a toaster message?

No, there is no toaster neither toasts 🍞 warning you that the game was saved.

> If not, could you make one?

Well, if the game happens to just be closed, since the project targets both mobile device**s** _and_ desktop, making a "toast" or any other kind of notification would not be easy (different for Windows, macOS, and accross Linux-based devices).
> It will give people feedback about their saved game.

But once you know the game is saved, which is going to happen always unless something goes horribly wrong or you don't have half kb available on your disk, then the toast might get a bit annoying, I mean, won't it? Because the file gets saved quite a few times (open menu, going the main screen or exiting the game). I think it's fine without a toast.

**Comment by StefanBrand** [comment]
Yes, your arguments have convinced me.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 16:36:55 MEZ schrieb Lonami <notifications@github.com>:
>> Is there also a toaster message?
>
>No, there is no toaster neither toasts 🍞 warning you that the game was
>saved.
>
>> If not, could you make one?
>
>Well, if the game happens to just be closed, since the project targets
>both mobile device**s** _and_ desktop, making a "toast" or any other
>kind of notification would not be easy (different for Windows, macOS,
>and accross Linux-based devices).
>> It will give people feedback about their saved game.
>
>But once you know the game is saved, which is going to happen always
>unless something goes horribly wrong or you don't have half kb
>available on your disk, then the toast might get a bit annoying, I
>mean, won't it? Because the file gets saved quite a few times (open
>menu, going the main screen or exiting the game). I think it's fine
>without a toast.
