### ISSUE TITLE
Ghost

### ISSUE THREAD

**Issue by Buranek** [LonamiWebs/Klooni1010#14]
I need function to show a ghost — where the block will be placed exaclty. It's really hard to set block where I want. Maybe you need to do something with it. Ghost would be nice. But that's not all. How about snapping to grid?

**Comment by XyLoNaMiyX** [comment]
> It's really hard to set block where I want.

Why is it that hard for you? Wherever you have the block, it will be placed. It rounds to the average position, so there should not be issues with it being placed too far (it should be placed wherever it is).

> How about snapping to grid?

I do like that, but maybe as a setting. Disabled by default.
