### ISSUE TITLE
Remove "bought" string from theme selection

### ISSUE THREAD

**Issue by mueller-ma** [LonamiWebs/Klooni1010#16]
since they are unlocked by default

**Comment by XyLoNaMiyX** [comment]
> since they are unlocked by default

Not anymore, wait until the next release :)

I'm waiting for someone to provide more themes. These won't be "free".

**Comment by mueller-ma** [comment]
@XyLoNaMiyX sry, just saw 2e864b00172810a1da35fdbfa2e728d12e7fb5ed

Can you use values/strings.xml so the app can be translated?

**Comment by XyLoNaMiyX** [comment]
> Can you use values/strings.xml so the app can be translated?

I did plan adding some [`.properties` localization](https://github.com/libgdx/libgdx/wiki/Internationalization-and-Localization), but for now, there is a very small amount of strings it's not even worth it. Probably in a future though.
