### ISSUE TITLE
Wrong game over message in time mode

### ISSUE THREAD

**Issue by sm4rk0** [LonamiWebs/Klooni1010#17]
It would be more precise to say "Time's out", or something like that when game is over because of the timeout. If you decide to change this, be careful not to rely on the game mode only, but on the reason for game over, too.

**Comment by XyLoNaMiyX** [comment]
Ugh, more people noticed! I used to put the excuse "Well _technically_, there are no more moves left _because_ the time is over and you can't move more pieces anymore".

> be careful not to rely on the game mode only, but on the reason for game over, too

Yes, of course :)

**Comment by Hitechcomputergeek** [comment]
But technically, there are more moves left, you just can't make them!
