### ISSUE TITLE
Squares in preview don't have same size

### ISSUE THREAD

**Issue by 115ek** [LonamiWebs/Klooni1010#2]
Hey! Great game - I like it very much.
But I would prefer the pieces in the preview to have the same size.
Maybe you've got your own opinion - it's only my thought.

![screenshot_20170207-222018](https://cloud.githubusercontent.com/assets/11771774/22712317/a005a2da-ed84-11e6-85c1-6150a259fc86.png)

**Comment by XyLoNaMiyX** [comment]
> Great game - I like it very much.

Thank you for the positive feedback!

> But I would prefer the pieces in the preview to have the same size.

Yeah, you're not the first one to complain. Thing is before they were oversized (the 1x1 would occupy as much as the 3x3) and I limited it to be, as much, twice as large as the board cells. I also had planned to add some padding so i.e. two 3x3 pieces wouldn't look as a 6x3 one.

> Maybe you've got your own opinion

Even though I do like it, I have another excuse. Some pieces are so big (5x1) that wouldn't normally fit (they'd need 1/2 of the screen, but there is only 1/3 available), and so they need to be shrinked. If they can shrink, why can't they grow? Furthermore, bigger pieces means they're easier to pick up, and also that their size animates upon picked.

This being said, fixing this issue would be as simple as replacing the mentioned 2 by a 1. But I'd like to hear back your opinion on my arguments :)

Feel free to aport more ideas if any, together we can build a better game than the original~

**Comment by 115ek** [comment]
Hmm. I see your points. But nevertheless it's very confusing - I picked up the 1x1 square several times and thought it will fill 3x3... 
What about moving the whole game up? (Decrease the spacing to the upper screen edge, there's still a lot of space).
I found an 1010 screenshot here: http://cdn9.staztic.com/app/a/6624/6624440/block-1010-21-0-s-307x512.jpg

As you can see, there's enough place, even to place 5x1.
What display size do you use?
Other suggestion: You can add a checkbox in settings that can switch between two layouts... One for small displays, and one for bigger ones.
![](http://cdn9.staztic.com/app/a/6624/6624440/block-1010-21-0-s-307x512.jpg)

**Comment by XyLoNaMiyX** [comment]
> What about moving the whole game up? (Decrease the spacing to the upper screen edge, there's still a lot of space).

I don't think the height is a limitation itself, but rather the width. On the original game, the pieces for you to pick up are smaller than the board cells, and when you pick these up, they grow to their size on board.

So yeah, I think best option will be that the sizes are, as much, as large as the on board cells. If they still don't fit, then they'll be shrinked. I could potentially make all the cells be the same size but I think more-than-necessary space would be wasted. At least the sizes will look more "unified" than how they look now.

**Comment by 115ek** [comment]
> On the original game, the pieces for you to pick up are smaller than the board cells, and when you pick these up, they grow to their size on board.
I think that's the best way. The essential point is, that all pieces in preview should have the same cell size. If the size of the actual board pieces differs is not important.

> At least the sizes will look more "unified" than how they look now.
That sounds very good :smile:

**Comment by XyLoNaMiyX** [comment]
So I've been trying to make some other kind of animation when you pick the piece but I don't really know what I could do for it to look nicer. All my attempts looked super odd so I give up on that for now. Furthermore I don't really like the way it works in the original game either. Oh well.
