### ISSUE TITLE
Unclear button function's

### ISSUE THREAD

**Issue by treakiandroid** [LonamiWebs/Klooni1010#20]
First of all, Thanks a lot for this grate Tetris like game! Bit when i go to settings I've got the problem that i am unsure about many oc the button functions. What effect has for example the hash (#) button?

Could you please add some explanation for that buttons, maybe like longpress shows description like in some android apps, or maybe some help pages where all functions are explained in detail.

Thanks a lot in advanced!

**Comment by Lonami** [comment]
Oh my, sorry! I completely missed this issue, probably opened it by accident and then it wasn't on my notifications anymore.

> What effect has for example the hash (#) button?

It's a grid, it toggles the "snap to grid" feature, and is intended ease issue 19 :P 

> Could you please add some explanation for that buttons

Where should that explanation go? Wiki? `README.md`? Its official site? I'm not sure about adding it in-game though!

**Comment by sm4rk0** [comment]
Some applications (QKSMS, Simple Notepad,...) solve this with a toast containing button's function description triggered by a long-tap on a button.
