### ISSUE TITLE
Change "share" button with "quit" button upon losing

### ISSUE THREAD

**Issue by zeroheure** [LonamiWebs/Klooni1010#23]
Hi 
Your game is really too addictive :-) 
One problem is that one can't quit easily, when the game end. One must press "home" first. 
For the sake of my mind and peaceful with my wife, please add a direct "quit" button when one lose the game.
Xavier

**Comment by Lonami** [comment]
I think we can change the "themes" button for "quit" (like a power-off) once you lose, so we still have 4 perfect buttons and nothing else. Also, thanks for your appreciation.
