### ISSUE TITLE
continue but lose your score

### ISSUE THREAD

**Issue by zeroheure** [LonamiWebs/Klooni1010#24]
Many have requested something like selectable time (because 30 seconds is too short). Here's another and may be more pleasant way : 
In the [lgames serie](http://lgames.sourceforge.net/), when you lose, you will be asked to continue but losing all your score. As  quick sample see [lbreakout2](http://lgames.sourceforge.net/LBreakout)

**Comment by Lonami** [comment]
There is already a [replay](https://github.com/LonamiWebs/Klooni1010/raw/master/android/assets/ui/x4.0/replay.png) button which does just that, restarts the game, you lose your score but the timer starts over. What's the issue?

**Comment by zeroheure** [comment]
Purpose is to continue with the same part (round ?) of game (parte de un juego). 
It would be : start playing against time, lose, continue at the same step but with score at zero.

It's a bit hard to explain for me, just play lbreakout and you will understand. I can also ask a spanish woman to translate from french to spanish.

**Comment by Lonami** [comment]
Okay, say you're playing the time mode and you can't place any more pieces. So instead losing, the board is cleared and the score is lost, but the game continues. Did I understand correctly?

It feels a bit unnatural (at first), though it could work. Maybe don't lose all points, but rather based on the amount of pieces?

**Comment by zeroheure** [comment]
No it's not that :
You're playing the time mode and you lose because there is no time left. But you could still add pieces. So instead losing, the score is lost, the board is not cleared and the game continue.

**Comment by Lonami** [comment]
Uhm… not quite sure of this.

**Comment by zeroheure** [comment]
I forgot some points. Let me restart the explanations:
Player is on the time mode. He lose because there is no time left (but there is room for pieces).
Now he can play a new game with a clean board, or continue on the same board.
If he chose to continue on the same board, the score is lost and restart at zero. He got 30 seconds again. 
He can't achieve high score (?).

Reasons for this are:
- it's less frustrating
- mens need to win :-)
- player have build a beautiful board and wants to finish it

Again, it's more easy to understand if you play a bit with lbreakout2.

**Comment by Lonami** [comment]
> If he chose to continue on the same board

Ah, on the *same* board, with the pieces laid out already. Well, this can be kind of cheaty, because you'd continue with certain advantage. Say you were preparing to make a 5-rows cleared at once, you could do this with this, and get a time boost.

> the score is lost and restart at zero

What would happen with the coins?

> He can't achieve high score (?)

So… what's the point of playing if you can't beat the highscore?

> * it's less frustrating

Time mode is meant to be hard 😅

> * mens need to win :-)

Men should keep their feet on the floor.

> * player have build a beautiful board and wants to finish it

Normal mode? Normal mode will even save the board if you leave the application.

**Comment by Lonami** [comment]
Sorry, I can't see future for this (I'm closing old issues). Board aren't supposed to be "beautiful"… they're just chance, you can make a new board very quickly!
