### ISSUE TITLE
more "magnetic" pieces

### ISSUE THREAD

**Issue by zeroheure** [LonamiWebs/Klooni1010#25]
Some touch screen are not very good or too old and it's not allways easy to add pieces at the right place. For example I often lose a few seconds because the game refuse the piece which is not exactly upon the right background.
The pieces could be more easily added at the right place with some "magnetic" feature. Dropping the pieces near the grid should be enough. This can be default or an option.

**Comment by Lonami** [comment]
There's already a "snap to grid" feature discussed on #14, but it's off by default.

**Comment by zeroheure** [comment]
Please re-open. The current "snap to grid" feature is not enough as it looks work with the pieces upon the exact position (?). While it should be a bit more permissive.

**Comment by Lonami** [comment]
> work with the pieces upon the exact position

Well, to the closest position it can find, yes. If you can't put the piece somewhere, it will not snap there, and it will *not* find the closest slot available. But if you dropped the piece right there (where you can't place it), it wouldn't do anything anyway.

There's no magic way to detect the user intention, and where they would want to put the pieces, so even if the magnet looked for the closest available position instead rounding to the desired one (just for a more visually appealing effect really), currently it simply will not put the piece.
