### ISSUE TITLE
Multiplier - No issue

### ISSUE THREAD

**Issue by VogelMoritz** [LonamiWebs/Klooni1010#26]
Hi Lonami! 

I love our game - it's the only game on my phone and I'm pretty addicted. 

But... what about multipliers? The more lines you clear, the higher the score you get? Like in Tetris, where clearing four lines have a higher value then clearing four times one line. 

Or is such a thing already implemeted and I just missed it?

**Comment by Lonami** [comment]
Such thing [is already implemented](https://github.com/LonamiWebs/Klooni1010/blob/master/core/src/io/github/lonamiwebs/klooni/game/BaseScorer.java#L76-L84) and you just missed it :)

I'm glad you enjoy the game, thanks for the feedback!

**Comment by Lonami** [comment]
You can calculate the same with this JavaScript code (<kbd>Ctrl+Shift+I</kbd> on Chrome or Chromium):
```javascript
function calculateClearScore(stripsCleared, boardSize) {
    if (stripsCleared < 1) return 0;
    if (stripsCleared == 1) return boardSize;
    return boardSize * stripsCleared + calculateClearScore(stripsCleared - 1, boardSize);
}

for (var i = 0; i <= 6; ++i) {
    console.log("Clearing "+i+" strips gives "+calculateClearScore(i, 10));
}
```

With this result:
```Clearing 0 strips gives 0
Clearing 1 strips gives 10
Clearing 2 strips gives 30
Clearing 3 strips gives 60
Clearing 4 strips gives 100
Clearing 5 strips gives 150
Clearing 6 strips gives 210```
