### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [LonamiWebs/Klooni1010#27]
<table><tr><td>
If you find any other application violating the GNU GPL v3 license, please comment it here so that we can take action. Thanks! <sub><i>-- Edit from @Lonami</i></sub>
</td></tr></table>

---

Hi @LonamiWebs

I found [this app](https://play.google.com/store/apps/details?id=net.pointapps.kubic) and also [this one](https://play.google.com/store/apps/details?id=com.vanpt.puzzGame), [this one](https://play.google.com/store/apps/details?id=oldschool.start.android.tenten) and [this one](https://play.google.com/store/apps/details?id=com.smart.game.tenten) on the Google Play Store. This guys just took your source code, added sometimes some ads in it and put it on the Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove each false app from the Store, if it's your wish ;) (I assume it will increase the number of downloads from the original app made by Gram Games too)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guys are violating it;
* They are falsely claiming they made the app.

Maybe add a link to this repo in the request, some screenshots of your original app...

Btw, thanks for this game :smile:

**Comment by sm4rk0** [comment]
@Poussinou Thank you for fighting for Free/Open Source Software! Do you have some crawling tools or you are doing this manually?

> Opened 22 other issues in 22 repositories"

**Comment by Poussinou** [comment]
I do not have "crawling tools" nor script, if it's your question, but I have now some "tips and tricks" (euphemism...) , and it's very easy for me now to find this kind of Free/Open Source Licenses violations...

I'll not explain in details my process (at least not here), since it could help violators to circumvent it^^

@Yonjuni

**Comment by Lonami** [comment]
Thing is… I tried contacting them a few times for the first link you posted (also thanks for showing me the other three I wasn't aware of). The package name seems to be unique so even if I got them down, I wouldn't be able to post the "original" . I already requested them to take the first one down for IP violation, but it seems like it's still up and running. I have emailed them a few times, but I will insist yet again. Thank you for the support!

**Comment by Poussinou** [comment]
@Lonami 

No problem ;)
Do not hesitate to contact Google then, if they don't want to remove their copies...

(This fake developers will probably read this discussion)

**Comment by Lonami** [comment]
I've added a little header on the issue description so that people knows they can report more applications here. This issue will remain open for said purpose :+1:

**Comment by Poussinou** [comment]
* https://play.google.com/store/apps/details?id=io.game.puzzle.legend.block
* https://play.google.com/store/apps/details?id=io.github.logiicsolution.klooni

**Comment by Poussinou** [comment]
@Lonami Here we go again https://play.google.com/store/apps/details?id=com.vision.elimination

**Comment by Poussinou** [comment]
Everything is done here.

I'm closing this Issue, but please report other copycats here in the future if you find some more.
