### ISSUE TITLE
Add new themes

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Klooni1010#29]
Design and contribute your **own theme** for Klooni! The only requirement is it has to be playable and not hurt players' eyes :)

To create a new theme, clone the repository, open `themes/create-theme.html` on a browser, and start designing. Then, show me your result and if it's pleasing enough we can integrate it in the application.

You can also **modify existing themes** to make the sprites or colours more pleasing. To modify or add **new sprites**, please use [Inkscape](https://inkscape.org/).

Preferrably, provide screenshots, they will make my task easier :)

For more information about the hacktoberfest and how you can get a free shirt, check out https://hacktoberfest.digitalocean.com.

**Comment by mhdsmr2** [comment]
What value should I set variable `price` to?

**Comment by Lonami** [comment]
That depends on how worthy you think your theme is, just don't make it horribly high or hilarously wrong. But most importantly, be original!

**Comment by mhdsmr2** [comment]
What's about 50?

**Comment by Lonami** [comment]
I haven't seen your theme so I don't know how worthy it is. Don't worry about it, I can always change it myself too.

**Comment by mhdsmr2** [comment]
Okay.

**Comment by Lonami** [comment]
Just a note for everyone else coming accross this issue, you can also **modify existing themes** slightly to make them more pleasing to the eye. Some of the sprites may not be the best, or some colours may fit awkwardly, so you could change those too!

**Comment by mhdsmr2** [comment]
Okay. We'll take care of that.

**Comment by mhdsmr2** [comment]
I have made a PR, please merge it. Thanks.
