### ISSUE TITLE
In default theme, cells color are difficult to see because it's too light

### ISSUE THREAD

**Issue by vinhnk** [LonamiWebs/Klooni1010#4]

**Comment by XyLoNaMiyX** [comment]
> ### cells color are difficult to see because it's too light

Do you mean the board empty cells and the background? What colours would you use? I wouldn't like a too-high contrast. You can pick them on http://colorpicker.com and let me know. I used the colors from the original game and, in my opinion, they look just fine.

**Comment by vinhnk** [comment]
I think the board empty cells and the background color of the original game is good to see :)

![screenshot_2017-02-15-20-09-07](https://cloud.githubusercontent.com/assets/19204113/22976232/80c9c728-f3bc-11e6-81e0-7e81610e0b61.png)

**Comment by XyLoNaMiyX** [comment]
> I think the board empty cells and the background color of the original game is good to see :)

Well… The thing is that I already use those colors, but swapped:
![captura de pantalla_2017-02-15_15-47-51](https://cloud.githubusercontent.com/assets/6297805/22979291/22d62f88-f396-11e6-8d1f-09803b15034a.png)

If I swap them:
![captura de pantalla_2017-02-15_15-48-50](https://cloud.githubusercontent.com/assets/6297805/22979327/48253658-f396-11e6-9899-0049eb09f0c5.png)

Okay just realised, problem is that the cell has already a very little dark tint (it's not 100% white) and then it + white → darkish. So it, yeah, you've got a point. I also like it swapped.
