### ISSUE TITLE
The package appears to be corrupt - download to android and install 

### ISSUE THREAD

**Issue by jacksnodgrass** [LonamiWebs/Klooni1010#44]
I ran the android build and had an apk created: 
build/outputs/apk/android-release-unsigned.apk
I downloaded to my android ( nougat  Samsum S8 )  
I see do you want to download.. I say Download followed by download complete. 
I click Install at the Do you want to install this application prompt and I get
1010! Kloone
App not installed
the package appears to be corrupt

and that's all she wrote... 

what am I missing?

- jack

**Comment by Lonami** [comment]
Probably because the `android-release` is not signed. I do my builds from within Android Studio which makes it easier to sign packages. See https://developer.android.com/studio/publish/app-signing.html.
