### ISSUE TITLE
Ads issue

### ISSUE THREAD

**Issue by kgullu** [LonamiWebs/Klooni1010#49]
I am developing different game with Klooni1010 based
But, when I add Google Ads my game I'm having trouble. adding ads.
There are some Gradle issue.
Please give advice. If you have experience.

**Comment by Lonami** [comment]
Uhmm, this isn't an issue with *my* version. Also, please remember to [comply with the license](https://github.com/LonamiWebs/Klooni1010/blob/master/LICENSE) once you publish your version.

**Comment by kgullu** [comment]
of  course.
and other question is : this game already including IOS gradle. 
can we compile for IOS.  if yes, how?
do you have any guide about it
thanks

**Comment by Lonami** [comment]
@kgullu no I don't have any guide. Refer to libGDX's documentation.
