### ISSUE TITLE
Current score is not displayed in time mode

### ISSUE THREAD

**Issue by StefanBrand** [LonamiWebs/Klooni1010#5]
In normal mode the current score is displayed where in time mode there is the countdown. So in time mode you only see the countdown and the highscore.

The time should be displayed somewhere else, maybe in the center?

**Comment by XyLoNaMiyX** [comment]
> The time should be displayed somewhere else, maybe in the center?

Maybe it should show:
<table>
<tr><td colspan="3">---------- time left ----------</td></tr>
<tr>
<td>current</td><td><b>cup</b></td><td>high</td>
</tr>
</table>

❓

**Comment by XyLoNaMiyX** [comment]
It looks like this:

![photo_2017-02-10_17-08-46](https://cloud.githubusercontent.com/assets/6297805/22833851/9b8f583c-efb3-11e6-9728-e24804559c5a.jpg)

Wonder if it's not a bit confusing…
