### ISSUE TITLE
Time mode is not challenging enough

### ISSUE THREAD

**Issue by StefanBrand** [LonamiWebs/Klooni1010#6]
I believe the time bonus is 5 seconds? It seems a bit too much and you usually loose because there is no space anymore and not because time runs out. Maybe 3 seconds time bonus is sufficient?

**Comment by XyLoNaMiyX** [comment]
> ### Time mode is not challenging enough

Completely agree! I'm not sure how it should be done though? Maybe less start time? Or less bonus? Should put pieces count? Should clearing strips give seconds differently than how it scores on the normal mode? Won't other users find it way too hard, or should it really be very challenging? Should the background blink on red like an alarm running low to make you rush?

> I believe the time bonus is 5 seconds?

Heh, not so simple. Time bonus is currently 1 second every 4 cells (either put, or cleared). This means when you clear a single strip it will as little add 2.75s.

**Comment by StefanBrand** [comment]
> Should the background blink on red like an alarm running
>low to make you rush?

I have always lost because space ran low, I never got to "time runs out" (I wouldn't have seen an alarm... The idea sounds good though!

> Should put pieces count?

What if only cleared cells counted in time mode?

--
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 16:52:41 MEZ schrieb Lonami <notifications@github.com>:
>> ### Time mode is not challenging enough
>
>Completely agree! I'm not sure how it should be done though? Maybe less
>start time? Or less bonus? Should put pieces count? Should clearing
>strips give seconds differently than how it scores on the normal mode?
>Won't other users find it way too hard, or should it really be very
>challenging? Should the background blink on red like an alarm running
>low to make you rush?
>
>> I believe the time bonus is 5 seconds?
>
>Heh, not so simple. Time bonus is currently 1 second every 4 cells
>(either put, or cleared). This means when you clear a single strip it
>will as little add 2.75s.

**Comment by XyLoNaMiyX** [comment]
> What if only cleared cells counted in time mode?

It would definitely make it more challenging, Hmm. 10 points (from clearing strip) = 2 seconds perhaps? Should the starting time be modified too? Because it takes a while to do some strips and that.

**Comment by StefanBrand** [comment]
If you like you can send me a beta build and I'll try it out! :)
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 20:17:59 MEZ schrieb Lonami <notifications@github.com>:
>> What if only cleared cells counted in time mode?
>
>It would definitely make it more challenging, Hmm. 10 points (from
>clearing strip) = 2 seconds perhaps? Should the starting time be
>modified too? Because it takes a while to do some strips and that.

**Comment by XyLoNaMiyX** [comment]
> If you like you can send me a beta build and I'll try it out! :)

I did think about you testing it. But more like _you_ playing with the values perhaps? Until you got a good feel of it. Anyway I do need to tweak some stuff so only the strips score. Not a big deal but it does need to be done. I have to play with the values a bit more.

**Comment by StefanBrand** [comment]
Oh, I won't have time for playing around with the values, unfortunately... Can only test ready-made builds and give feedback atm... :blush: 
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 23:36:50 MEZ schrieb Lonami <notifications@github.com>:
>> If you like you can send me a beta build and I'll try it out! :)
>
>I did think about you testing it. But more like _you_ playing with the
>values perhaps? Until you got a good feel of it. Anyway I do need to
>tweak some stuff so only the strips score. Not a big deal but it does
>need to be done. I have to play with the values a bit more.

**Comment by XyLoNaMiyX** [comment]
> Can only test ready-made builds and give feedback atm

Uploaded them to [Google Drive](https://drive.google.com/drive/folders/0ByWAUHi-90iQY3hmYnpZWVpSbXM?usp=sharing), both for Android and desktop. I recommend you to test the desktop build, because the `.apk` file will have a different signature than F-Droid's and you would have to uninstall and lose your high score etc.

**Comment by StefanBrand** [comment]
Sorry, I don't understand what you mean with the scores... :/ 

I didn't get around to test your debug build, but I played 0.3 and found it a lot better at start. Later on, the time rises fast and it's not challenging, if you have 100 seconds "in stock".

**Comment by XyLoNaMiyX** [comment]
> I didn't get around to test your debug build

I was just playing around with the new values and it's a bit crazy. Like, I like it's so challenging. If you manage to clear 3/4 strips you get a lot ("a lot") of time, so you either clear a lot often, or plan to do a big one. I don't know. It's too challenging (and I'm using a mouse). But if I pump up the time to 3 seconds per strip, then it feels easy. Not sure. But really, people who plays this new mode should not get stressed easily or they'll go mad.

**Comment by StefanBrand** [comment]
Isn't the purpose of a time mode to "go mad"? :D

**Comment by XyLoNaMiyX** [comment]
> Isn't the purpose of a time mode to "go mad"? :D

Yeah but kinda sucks if you don't even manage to clear a strip!

**Comment by XyLoNaMiyX** [comment]
Wrong button.

**Comment by StefanBrand** [comment]
What if countdown starts at 30 seconds?

**Comment by XyLoNaMiyX** [comment]
> What if countdown starts at 30 seconds?

I tried. 30 feels too high. 20 feels to low. I don't like 25. We have a problem here :/

**Comment by StefanBrand** [comment]
What about an easy, a moderate and a hard mode?

**Comment by XyLoNaMiyX** [comment]
> What about an easy, a moderate and a hard mode?

Not seeing it coming.

**Comment by StefanBrand** [comment]
Who is the target group of the time mode then? The casual player or the 
advanced player, who searches for a more challenging game?

Am 17.02.2017 um 17:13 schrieb Lonami:

**Comment by XyLoNaMiyX** [comment]
> Who is the target group of the time mode then? The casual player or the
advanced player, who searches for a more challenging game?

I think it should just be challenging. Could you test the build?

**Comment by XyLoNaMiyX** [comment]
Gotta change the scoring system now, rather than time alive, the pieces score. I think it's more fair.
