### ISSUE TITLE
Can't run build jar due to java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by raLaaaa** [LonamiWebs/Klooni1010#65]
Hey there,

I imported the project to my IntelliJ.
Afterwards I ran the `./gradlew desktop:dist` command from the root project folder.
Output states that the build has been succesfull.

Afterwards I run the build .jar with `java -jar xxx.jar`

It then states the following exception;

`java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener` (sounds a little bit like my system can't find libgdx in the build .jar)

When trying trying to start the DesktopLauncher manually via my IDE the following exception comes up:

`Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: ic_launcher\icon128.png (Internal)`

I'm using newest IntelliJ Community Edition, Java 9 and build in Intellij Gradle. Any ideas why this happens? I'm assuming that it's a problem on my side. 

Help or hints are much appreciated! Thanks for your work.

**Comment by Lonami** [comment]
Maybe we shouldn't update gradle. See this [answer on java.lang.NoClassDefFoundError (libgdx)](https://stackoverflow.com/a/47484688).

**Comment by raLaaaa** [comment]
Ah thanks for the reply. What a pity.

**Comment by Lonami** [comment]
I've re-ran the setup and used those files, pushed in commit https://github.com/LonamiWebs/Klooni1010/commit/9c6be35369a7bb07d11838e4cc84f7cb3efcf338. Could you try again? I've seen some fixes for the weird things one had to do before to change the assets location.

**Comment by raLaaaa** [comment]
Thanks for your help. It still doesnt work but if i try to run the build application it now also displays the following exception:

It can find the application listener though. So I think it's a step towards the right direction?

`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: ic_launcher/icon128.png`

**Comment by Lonami** [comment]
It's weird it still fails like that. Note [this line of the mentioned commit](https://github.com/LonamiWebs/Klooni1010/commit/9c6be35369a7bb07d11838e4cc84f7cb3efcf338#diff-a4eba195fd8e48a2d5d1dbed22717b5bR5), it points to the [`android/assets`](https://github.com/LonamiWebs/Klooni1010/tree/master/android/assets) folder which contains the [`ic_launcher/icon128.png`](https://github.com/LonamiWebs/Klooni1010/blob/master/android/assets/ic_launcher/icon128.png) file. I'm not sure why it's failing right now.

**Comment by raLaaaa** [comment]
Copying assets in the working directoy fixed it for me! No idea why it exactly did not work though. Thanks for the help!
