### ISSUE TITLE
Main screen's menu seems overly zoomed-in

### ISSUE THREAD

**Issue by tigresansrayure** [LonamiWebs/Klooni1010#66]
Hello,

I'm using a Fairphone 3 with Android 9 (latest update from April 6, 2020, with kernel 4.9.112), and the main screen's menu is "out of the screen", it seems that it's zoomed-in.
See the screenshot below.

( otherwise thanks for this great game ! :) )

![image](https://user-images.githubusercontent.com/21152917/81666157-f3113e00-9441-11ea-91df-d2a5e0ea6070.png)

**Comment by Lonami** [comment]
Yeah, that looks bad, wonder if #8 has anything to do. I'm not really sure what the proper solution is though, and I haven't touched libGDX in a while.

**Comment by DrizztFR** [comment]
Hello. If that helps I get the exact same screen on Xiaomi Mi Mix 2S with LineageOS 16 (Android 9)

**Comment by darhma** [comment]
Same issue on xiaomi redmi note 7 with lineageos 17.1 (android 10)

**Comment by oxr463** [comment]
Motorola G7 with LineageOS 16.0

**Comment by Lonami** [comment]
Did this happen with older versions (0.8.3 and below)? It might be https://github.com/LonamiWebs/Klooni1010/commit/9c6be35369a7bb07d11838e4cc84f7cb3efcf338 if not because there haven't been other large changes. Maybe libGDX behaves differently now.

**Comment by darhma** [comment]
Just installed version 0.8.3 from play store (aurora store) and it looks fine. Both versions on f-droid (0.8.4 and 0.8.5) have the problem on the home screen

**Comment by Lonami** [comment]
Those versions are post the libGDX upgrade, so perhaps #8 is not needed anymore. Needs investigation.

**Comment by Lonami** [comment]
It's embarrasing it took me so long to configure the build environment when the fix was a single line…

**Comment by Lonami** [comment]
> I have the oversized start screen issue #66

That issue should be fixed. Do you still have the issue in the latest version @RustanHakansson (or anyone else who experienced it)?

**Comment by RustanHakansson** [comment]
This is fixed now, but was not when I got confused before.
