### ISSUE TITLE
Countdown time mode accidentally activated?

### ISSUE THREAD

**Issue by RustanHakansson** [LonamiWebs/Klooni1010#69]
When I activate grid I also activate the countdown mode. I see no other reference to the countdown mode. Is this intentional?

**Comment by Lonami** [comment]
What version are you using? Are you talking about the "snap to grid" setting in the customization menu? If you're on the latest version, could you include a video of the issue? I cannot reproduce.

**Comment by RustanHakansson** [comment]
I have the oversized start screen issue #66 . It might have been that I accidentally clicked the blue button after switching to grid, cannot reproduce.
