### ISSUE TITLE
Display time bonus after row/column is cleared

### ISSUE THREAD

**Issue by StefanBrand** [LonamiWebs/Klooni1010#7]
This could be a nice feature: display "+5" (or whatever time bonus there is) above the cleared row/column and let it fade out.

**Comment by XyLoNaMiyX** [comment]
I see this. A text appearing from the centre of gravity of the put piece with size 0, then growing to it's normal size, then going upwards slowly and fading! So cool! Oh. I hope that's not hard to do or I'll regret dreaming awake.

**Comment by XyLoNaMiyX** [comment]
It looks soooo good! 💯

**Comment by StefanBrand** [comment]
Looking forward to see it live! :D 
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 10. Februar 2017 18:29:45 MEZ schrieb Lonami <notifications@github.com>:
>It looks soooo good! 💯
