### ISSUE TITLE
Official desktop build?

### ISSUE THREAD

**Issue by infeeeee** [LonamiWebs/Klooni1010#74]
I tried to build following the documentation, but couldn't set up android sdk, and gave up. Can you post desktop .jar builds here on github or on the website? I guess you have a working development setup unlike me...

**Comment by Lonami** [comment]
For the time being, 0.8 is downloadable as a `.jar` for use in Desktop in the [releases page](https://github.com/LonamiWebs/Klooni1010/releases). But I forgot to publish the latest version indeed.

**Comment by infeeeee** [comment]
Ahh, so I should just scrolled down a bit. I had a feeling that it's uploaded, but I'm just blind... Thank you!

**Comment by Lonami** [comment]
Let's keep this open until I remember to publish an up-to-date `.jar`.

**Comment by Lonami** [comment]
Can't forget now! :)

Figuring out how to slightly alter environment variables took way longer than expected, but hey, it's done.
