### ISSUE TITLE
How to view and change game logic

### ISSUE THREAD

**Issue by OwenSlevin** [LonamiWebs/Klooni1010#76]
How can I edit the game files to modify the game to my liking? I don't see any files containing game logic so has everything been imported through libraries? 

I see the .so files which are dynamic libraries in binary? If it's binary I imagine I shouldn't mess with them then?

Any advice would be appreciated. I'm a novice trying to improve my android dev skills and figured this would be a good place to start since it's been my go to app for a while.

**Comment by 9ary** [comment]
bruh
