### ISSUE TITLE
Add nord theme

### ISSUE THREAD

**Issue by sheeepdev** [LonamiWebs/Klooni1010#77]
Can u add nord theme plz

**Comment by Lonami** [comment]
I don't have the time to do it, but if you want, you can copy an existing theme in https://github.com/LonamiWebs/Klooni1010/blob/master/android/assets/themes to `nord.theme` and add then add it to the [`theme.list`](https://github.com/LonamiWebs/Klooni1010/blob/master/android/assets/themes/theme.list). After you're done, send a pull request with screenshots and we can check how good it looks :)

**Comment by sheeepdev** [comment]
ok! thanks.

**Comment by sheeepdev** [comment]
not sure tho but i dont know this stuff I would do it but yeah
