### ISSUE TITLE
Suggestion for screenshot naming

### ISSUE THREAD

**Issue by yashpalgoyal1304** [LonamiWebs/Klooni1010#78]
![image](https://user-images.githubusercontent.com/19423063/120828395-1c839700-c57a-11eb-92bc-e1b7b0c4fc4f.png)

The much much more predictable naming pattern is just plain consecutive numbers. it helps in lots of corner bug cases.

**Comment by Lonami** [comment]
What bugs?

**Comment by yashpalgoyal1304** [comment]
not the bug in ur app, but the bugs while browsing in fdroid website/client app etc. like today, i couldnt make it to go to 3rd screenshot. 

And also, since fdroid doesnt provide the dedicated image viewer for the screenshot, the predictable naming will also help when screenshots are opened in new tab --> just change the link from 1, to 2, to 3, and done.

**Comment by Lonami** [comment]
Would you like to send a pull request?
