### ISSUE TITLE
Themes Not Working on Desktop

### ISSUE THREAD

**Issue by jeremytuttle119** [LonamiWebs/Klooni1010#81]
Hello!  Great 1010 clone app.  Well written and great commentary in the files.  This comes at a great time since the original 1010! app has been ruined via "power-ups" and "retries", which defeats the purpose of the game.

Issue: when I compile the desktop version and run the .JAR, the themes aren't showing up in the menu.  See attached pic.  I've verified that the themes, and the themes.list file, exist in the project.

![no_themes](https://github.com/LonamiWebs/Klooni1010/assets/61870597/3a81009e-c680-402b-9fd4-2bf11e65a95e)

**Comment by Lonami** [comment]
Thanks for the kind words, unfortunately I haven't tried building or updating this application in forever, so I can't remember much.

It sounds like you may not have correctly setup the path for the assets though. If I remember correctly, at least from Android Studio, you had to set the desktop project to build with android's assets, or something along those lines.

Could try copying the assets folder or changing the working directory.

**Comment by jeremytuttle119** [comment]
> Thanks for the kind words, unfortunately I haven't tried building or updating this application in forever, so I can't remember much.
> 
> It sounds like you may not have correctly setup the path for the assets though. If I remember correctly, at least from Android Studio, you had to set the desktop project to build with android's assets, or something along those lines.
> 
> Could try copying the assets folder or changing the working directory.

That's probably it - I am using Gradle with an Android SDK plug-in so that Android Studio doesn't have to be used (or even installed).  It's probably not linking the assets properly because of this.  I'll confirm later and reply here.  Thanks so much for the reply!!

**Comment by jeremytuttle119** [comment]
Was definitely a problem linking to the assets library - closing issue!
