### ISSUE TITLE
Back buttun?

### ISSUE THREAD

**Issue by remibemol** [LonamiWebs/Klooni1010#9]

**Comment by XyLoNaMiyX** [comment]
The back button shows the menu on the game screen, and goes to the previous screen on all the other screens. What's your issue? Is this for desktop? You can press <kbd>P</kbd> for **P**ause on desktop (on the game screen).

**Comment by XyLoNaMiyX** [comment]
Not enough information provided. Add more and I'll open the issue so we can discuss about it. Closing this not to add noise to the issues section.
